# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'digest'
require 'open-uri'
require 'json'

default_platform(:ios)

desc 'Prepare cached media files for storysdk'
lane :prepare_story_cache do |options|
  cache_onboarding(options[:group])
end

def cache_onboarding(group_id)
  cache = {}

  response = JSON.parse(URI.open("https://api.storysdk.com/sdk/v1/groups/#{group_id}/stories").read)
  raise StandardError, response["error"] unless response["error"].empty?

  data = response["data"]

  data.each do |item| 
    widgets = item["story_data"]["widgets"]
    widgets.each do |widget|
      video_url = widget["content"]["params"]["videoUrl"]

      puts video_url

      unless video_url.nil?
        digest = Digest::SHA256.hexdigest video_url
        key = File.basename(video_url)
        ext = File.extname(video_url)

        Dir.mkdir('./cached') unless Dir.exist?('./cached')
        File.open("./cached/#{digest}#{ext}", 'wb') do |file|
          file << URI.open(video_url).read
        end

        cache[key] = "#{digest}#{ext}"
      end
    end
  end
end
